# Generated by Django 5.2.4 on 2025-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama area layanan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat area layanan', null=True)),
                ('latitude', models.FloatField(help_text='Koordinat latitude titik pemancar')),
                ('longitude', models.FloatField(help_text='Koordinat longitude titik pemancar')),
                ('coverage_radius_km', models.FloatField(default=1.0, help_text='Radius jangkauan sinyal (km)')),
            ],
        ),
    ]
